.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "SEGFAULT\-BUILD" "8" "January 2020" "debug-misc" "debug-misc Manual"
.SH "NAME"
\fBsegfault\-build\fR \- create segfault\-run program
.SH "SYNOPSIS"
segfault\-build
.SH "DESCRIPTION"
Creates \fBsegfault\-run\fR\.
.SH "RETURN VALUES"
0 success\.
.P
Non\-zero otherwise\.
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
